// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cleaner} from '../models';
import {main} from '../models';

export function ChooseExportPath(arg1:string,arg2:string):Promise<string>;

export function CompareFiles(arg1:string,arg2:string,arg3:cleaner.Options):Promise<main.ComparisonResult>;

export function ExportReport(arg1:main.ComparisonResult,arg2:string,arg3:string):Promise<void>;

export function GetMachineCode():Promise<string>;

export function LicenseStatus():Promise<main.LicenseStatus>;

export function PickDocument():Promise<string>;

export function VerifyLicense(arg1:string):Promise<void>;
