// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseExportPath(arg1, arg2) {
  return window['go']['main']['App']['ChooseExportPath'](arg1, arg2);
}

export function CompareFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompareFiles'](arg1, arg2, arg3);
}

export function ExportReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportReport'](arg1, arg2, arg3);
}

export function GetMachineCode() {
  return window['go']['main']['App']['GetMachineCode']();
}

export function LicenseStatus() {
  return window['go']['main']['App']['LicenseStatus']();
}

export function PickDocument() {
  return window['go']['main']['App']['PickDocument']();
}

export function VerifyLicense(arg1) {
  return window['go']['main']['App']['VerifyLicense'](arg1);
}
